MyWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomePage.urls')),
    path('comment/', include('comment.urls')),
    path('accounts/', include('accounts.urls')),
    path('friend/', include('Friends.urls')),
]

comment/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='comment'
urlpatterns = [
    path('', views.comment_listed, name='comment'),
    path('comment_create/', views.comment_create, name="comment_create"),
    path('replying/<int:comment_id>', views.replying, name="reply"),
    path('liking/', views.liking, name="like")
]

comment/models.py
from django.db import models
from django.contrib.auth.models import User

class Comment(models.Model):
    username = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} - {}".format(self.username, self.snipped_message())
    
    def snipped_message(self):
        if len(self.comment) > 20 :
            return self.comment[:20] + " ..."
        return self.comment
    
class Reply(models.Model):
    username = models.ForeignKey(User, default=None, on_delete=models.CASCADE, blank=True, null=True, related_name="user")
    reply_message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, blank=True, null=True, related_name="replies")
    def __str__(self):
        return self.reply_message

class Like(models.Model):
    username = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.username)

comment/forms.py
from . import models
from django import forms

class CreateCommentForm(forms.ModelForm):
    
    comment = forms.CharField(widget=forms.Textarea(attrs={
            "class" : "fields",
            "required" : True,
            "placeholder":"Your Message",
             }))
    
    class Meta:
           model = models.Comment
           fields = ["comment"]

class CreateReplyForm(forms.Form):
    replies = forms.CharField(widget=forms.Textarea(attrs={
            "class" : "fields",
            "required" : True,
            "placeholder":"Reply here",
             }))
    class Meta:
           model = models.Comment

comment/views.py
from django.shortcuts import render, redirect
from .import forms
from .models import Comment, Reply, Like
from django.contrib.auth.decorators import login_required

def comment_listed(request):
    response = {
         'comment' : Comment.objects.all(),
         'form' : forms.CreateCommentForm(),
         'reply_form' : forms.CreateReplyForm(),
         'likes' : len(Like.objects.all()),
         'first3like' : Like.objects.all()[:3],
         'restlike' : len(Like.objects.all())-3,
    }
    return render(request, 'comment/comments_page.html', response)

@login_required(login_url="/accounts/login")
def comment_create(request):
    comment_form = forms.CreateCommentForm(request.POST)
    if request.method == "POST" and comment_form.is_valid():
        a= comment_form.save(commit=False)
        a.username = request.user
        a.save()
    return redirect('comment:comment')
  
@login_required(login_url="/accounts/login")
def replying(request, comment_id):
    reply_form = forms.CreateReplyForm(request.POST)
    if request.method == "POST" and reply_form.is_valid():
        Reply.objects.create(
            username = request.user,
            reply_message = reply_form.cleaned_data['replies'],
            comment = Comment.objects.get(id=comment_id),
        )        
    return redirect('comment:comment')

@login_required(login_url="/accounts/login")
def liking(request):
    usr = request.user
    for like in Like.objects.all():
        if like.username == usr:
            return redirect('comment:comment')
    Like.objects.create(
        username = request.user
    )
    return redirect('comment:comment')

comment/templates/comment/comments_page.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
    {% block content%}
    
    </div>

    <div class= 'BlockContent'>
        <h6>Likes & Comments</h6>
        <div class="test">
            <div class="likebox test">
                <h>{{ likes }}</h>
                <p class="smaller">
                {% if likes > 1 %}
                    Likes
                {% else %}
                    Like
                {% endif %}
                </p>
                <form method="POST" action="{% url 'comment:like' %}">
                    {% csrf_token %}
                    <button type="submit" class='formbutton animation'>LIKE</button>
                </form>
                <p>
                {% if likes > 0 %}
                    {% for usr in first3like %} 
                        {{ usr.username }}, 
                    {% endfor %}
                    {% if restlike >= 1 %}
                        and {{ restlike }} other
                    {% endif %}
                    liked this Web
                {% endif %}
                </p>
            </div>
        </div>
        <div><br><br>
        <h6 class="justatext">Comments</h6>
        {% for coment in comment %}
            <div class="cmntbox">
                <h3>{{ coment.username }}</h3>
                <p class="date">{{ coment.created_at }}</p>
                <p class="txt">{{ coment.comment }}</p>
                <button class="hbutton hidebutt"  id="b{{ coment.id }}" onclick="Hide({{ coment.id }})">See Reply</button>
                <div class='rplybox' id="{{ coment.id }}">
                    {% for rply in coment.replies.all %}
                        <div class='line'>
                            <h3>{{ rply.username }}</h3>
                            <p class="date">{{ rply.created_at }}</p>
                            <p class="txt">{{ rply.reply_message }}</p>
                        </div>
                    {% endfor %}
                    <form  method="POST" action="{% url 'comment:reply' comment_id=coment.id %}">
                        {% csrf_token %}
                        <div>
                            {% for field in reply_form.visible_fields %}
                                {{ field }}
                            {% endfor %}
                        </div>
                        <button type="submit" class='submitbutton'>Reply</button>
                    </form>
                </div>
            </div>
        {% endfor %}
        </div>
        <div class="forme">
            <form action="{% url 'comment:comment_create' %}" method="POST">
                {% csrf_token %}
                <div>
                    {% for field in form.visible_fields %}
                        <div>{{ field }}</div>
                    {% endfor %}
                    <button type="submit" class="submitbutton">Send</button>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">
    function Hide(ID) {
        if (document.getElementById(ID).style.display=="block") {
            document.getElementById('b'+ID).innerHTML='See Reply';
            document.getElementById(ID).style.display='none';
        }

        else {
        document.getElementById('b'+ID).innerHTML='Hide Reply';
        document.getElementById(ID).style.display='block';
        }
    }
    </script>
    {% endblock %}