MyWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomePage.urls')),
    path('comment/', include('comment.urls')),
    path('accounts/', include('accounts.urls')),
    path('friend/', include('Friends.urls')),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.loggedin, name='login'),
    path('logout/', views.loggedout, name='logout'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_page.html', {'form':form})

def loggedin(request):
    if request.method ==  'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('HomePage:homepage')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login_page.html', {'form':form})
    
def loggedout(request):
    if request.method == 'POST':
        logout(request)
        return redirect('HomePage:homepage')

accounts/templates/accounts/login_page.html
{% extends 'base_layout.html' %}

{% block content %}

    </div>
    <div class='BlockContent test'>
        <div class="form">
            <center><h2>LOGIN</h2></center>
            <form action="/accounts/login/" method="POST" class="test mid" style="color:white">
                {% csrf_token %}
                <div class="unknown"><p>Username</p>{{ form.username }}</div>
                <div class="unknown"><p>Password</p>{{ form.password }}</div>
                <div class="unknown test">
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    <p class='formlink test'><a href="{% url 'accounts:signup' %}">Don't have an Account? SignUp Here</a></p>
                    <button type="submit" class="formbutton">Login</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accounts/templates/accounts/signup_page.html
{% extends 'base_layout.html' %}
{% block content %}

    </div>
    <div class='BlockContent test'>
        <div class="form">
            <center><h2>SIGNUP</h2></center>
            <form action="/accounts/signup/" method="POST" class="test mid" style="color:white">
                {% csrf_token %}
                <div class="unknown"><p>Username</p>{{ form.username }}</div>
                <div class="unknown"><p>Password</p>{{ form.password1 }}</div>
                <div class="unknown"><p>Confirm Password</p>{{ form.password2 }}</div>
                <div class="unknown">
                    <p><button id='bHID' onclick="Hide()">Hint</button></p>
                    <ul id="HID" class="hidden">
                        <li>Your password can't be too similar to your other personal information.</li>
                        <li>Your password must contain at least 8 characters.</li>
                        <li>Your password can't be a commonly used password.</li>
                        <li>Your password can't be entirely numeric.</li>
                    </ul>
                </div>
                <div class="unknown test">
                    <p class='formlink test'><a href="{% url 'accounts:login' %}">Already have an Account? LogIn Here</a></p>
                    <button type="submit" class="formbutton">Signup</button>
                </div>
            </form>
        </div>
    </div>

    <script type="text/javascript">
        function Hide() {
            if (document.getElementById('HID').style.display=="block") {
                document.getElementById('bHID').innerHTML='Hint';
                document.getElementById('HID').style.display='none';
            }

            else {
            document.getElementById('bHID').innerHTML='Hide';
            document.getElementById('HID').style.display='block';
            }
        }
        </script>
{% endblock %}