Friends/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views
app_name='Friends'
urlpatterns = [
    path('friends/', views.friendlist, name='friend'),
    path('add_friend/', views.add_friend, name='add_friend'),
    path('detail/<slug>/', views.friend_detail, name='detail'),
]

HomePage/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='HomePage'
urlpatterns = [
    path('', views.index, name='homepage')
]

MyWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HomePage.urls')),
    path('comment/', include('comment.urls')),
    path('accounts/', include('accounts.urls')),
    path('friend/', include('Friends.urls')),
]

accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.loggedin, name='login'),
    path('logout/', views.loggedout, name='logout'),
]

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
    <title>Leonardo</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet"  href="{% static 'style.css' %}">
    </head>
    <body>
        <div class="topnav">
            {% if user.is_authenticated %}
            <form action="/accounts/logout/" method="POST">
                {% csrf_token %}
                <a><button type="submit" class='hbutton'>Logout</button></a>
            </form>
            <a href="{% url 'Friends:add_friend' %}">{{ request.user }}</a>
            {% else %}
            <a href="{% url 'accounts:login' %}">Login</a>
            {% endif %}
            <a href="{% url 'Friends:friend' %}">Friends</a>
            <a href="/comment">Comment</a>
            <a href="{% url 'HomePage:homepage' %}">HOME</a>
            
            {% block content%}
            {% endblock %}

            <div class="sosmedbox" id="sosmed">
                <h1>Follow Me</h1>
                <div class="ssbox" id="line">
                    <div class="mid">
                        <a href="https://line.me/en-US/" target="_blank">
                            <h2><b>Line</b></h2>
                            <h3>ID : leonardo2000</h3>
                        </a>
                    </div>
                </div>
                <div class="ssbox" id="instagram">
                    <div class="mid">
                        <a href="https://www.instagram.com/leonardo7820/" target="_blank">
                            <h2><b>Instagram</b></h2>
                            <h3>@leonardo7820</h3>
                        </a>                    
                    </div>
                </div>
                <div class="ssbox" id="gmail">
                    <div class="mid">
                        <a href="https://www.gmail.com/" target="_blank">
                            <h2><b>Gmail</b></h2>
                            <h4>leonardoeinstein2000@gmail.com</h4>
                        </a>
                    </div>
                </div>    
            </div>  
        </body>
    </html>